### ISSUE TITLE
Set ->path() to the image upload.

### ISSUE THREAD

**Issue by stufarquhar** [ctessier/nova-advanced-image-field#15]
Hi there, just wondering if the upload to S3 is working with the ->path() function. it seems to throw it in the root of the bucket.

Cheers

**Comment by ctessier** [comment]
Hi @stufarquhar, you are right. Because the `UploadedFile` is transformed into an instance of 
`Intervention\Image`, we don't benefit from the `store` and `storeAs` methods that the native `File` field uses.
If you think of a way to edit the image on the server while keeping the instance of `UploadedFile`, I am interested of course.

As a workaround though, I guess you can still create a custom disk in `filesystems.php` for each directory you may need. But I agree, that can become cumbersome.

I want to stick to the `File` interface as much as I can, so I will keep digging to find a better solution.

**Comment by h-zone** [comment]
> If you think of a way to edit the image on the server while keeping the instance

`Observer > saved`

This will make need to create a trait (?) or entirely mophable configurable model with ability to move file after placement to proper place at filesystem

**Comment by ctessier** [comment]
Fixed by #29
