### ISSUE TITLE
Image Size/Quality 

### ISSUE THREAD

**Issue by elcuniado** [ctessier/nova-advanced-image-field#23]
Images size is almost twice more than the original size after upload and also the quality is worse.

Code:
`AdvancedImage::make('Photo')->croppable()->resize(1500, 900)`

Please have a look what is the issue.
It's a very necessary package,  I love it :)

Thank You !!!

![issue](https://user-images.githubusercontent.com/45648028/56853194-a0431200-6924-11e9-901d-7efdde1a4f42.jpg)

**Comment by ctessier** [comment]
Hi @elcuniado, first thank you very much for your feedback!
The package uses GD and  [Intervention Image resize method](http://image.intervention.io/api/resize) to resize images. This issue could be related to one of these.
I will try to have a look asap and try to understand why you get this result. In the mean time, feel free to submit a PR if you find a fix on the package.
Good day!

**Comment by ctessier** [comment]
Hi @elcuniado, I ran into [this article](https://stackoverflow.com/questions/13257405/why-is-resized-png-image-so-much-bigger-than-original-image/13258023#13258023) which may be interesting for your case.

I tried to reproduce on my side but I personally got a smaller image.
If you can send me your original image, I can try again and maybe see if I get any different result using Imagick instead of gd.

Have a good day!

**Comment by ctessier** [comment]
Closing the issue.
Feel free to reopen if you still have the problem.
