### ISSUE TITLE
Issue with svg upload

### ISSUE THREAD

**Issue by sonalmahajan01** [ctessier/nova-advanced-image-field#54]
When i try to upload svg files with this uploader, it gives format error.

`Encoding format () is not supported. {"userId":21,"exception":"[object] (Intervention\\Image\\Exception\\NotSupportedException(code: 0): Encoding format () is not supported. at /var/www/vendor/intervention/image/src/Intervention/Image/AbstractEncoder.php:173)
[stacktrace]
#0 /var/www/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php(79): Intervention\\Image\\AbstractEncoder->process(Object(Intervention\\Image\\Image), '', NULL)
#1 /var/www/vendor/intervention/image/src/Intervention/Image/Image.php(121): Intervention\\Image\\AbstractDriver->encode(Object(Intervention\\Image\\Image), '', NULL)
#2 /var/www/vendor/intervention/image/src/Intervention/Image/Image.php(146): Intervention\\Image\\Image->encode('', NULL)
#3 /var/www/vendor/ctessier/nova-advanced-image-field/src/TransformableImage.php(136): Intervention\\Image\\Image->save()
#4 /var/www/vendor/ctessier/nova-advanced-image-field/src/AdvancedImage.php(66): Ctessier\\NovaAdvancedImageField\\AdvancedImage->transformImage(Object(Illuminate\\Http\\UploadedFile), Object(stdClass))`

**Comment by ctessier** [comment]
Hi @sonalmahajan01,

Thank you for your feedback.

Unfortunately, Intervention/Image doesn't support SVG files (http://image.intervention.io/getting_started/formats).

You get this error because you are trying to resize or crop the SVG file, which is not supported by GD or Imagik anyway.

If you want to upload the SVG, you should use the native Nova field, or don't configure cropping or resizing.

I hope this helps.
Clément
